SensitivityAnalysis - use "by path" methods
esqLABS/esqlabsR pull request #271
Opened 2022-07-18 13:11 UTC by PavelBal

Fixes #269

2022-07-18 13:12 UTC, PavelBal commented
This PR avoids creating `Parameter` objects and uses the `byPath` methods implemented in ospsuite.

2022-07-18 13:32 UTC, IndrajeetPatil requested changes

2022-07-18 13:36 UTC, IndrajeetPatil commented
Hmm, are _ospsuite_ binaries not up to date?

```r
== Failed tests ================================================================
  -- Error (test-sensitivity-calculation.R:26:1): (code run outside of `test_that()`) --
  Error: 'getQuantityValuesByPath' is not an exported object from 'namespace:ospsuite'
  Backtrace:
      x
   1. \-esqlabsR::sensitivityCalculation(...) at test-sensitivity-calculation.R:26:0
  
  [ FAIL 1 | WARN 6 | SKIP 0 | PASS 114 ]
```

We are fetching them from here: https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/ospsuite-r/artifacts/ospsuite.zip

2022-07-18 14:05 UTC, PavelBal commented
Damn, this is due to https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1017. Will probably have to wait until Michael triggers a PK-Sim build....

2022-07-19 09:27 UTC, PavelBal commented on R/sensitivityCalculation.R
> +    )) {
OK done.

2022-07-19 09:28 UTC, IndrajeetPatil approved these changes

2022-07-19 09:41 UTC, IndrajeetPatil commented
I am looking into the failing example.

2022-07-19 10:15 UTC, PavelBal commented
This is strange, why does it work locally?

Unlocking means that the user could add new fields AFTER creation of the object, which is not good. "Cannot add bindings" implies that `defaultPlotConfiguration$legendCaptionSize` is not present in the class, but it actually is... It also works locally.

2022-07-19 10:21 UTC, PavelBal commented
@IndrajeetPatil Did you remove the field `legendCaptionSize` from default plot configuration at some point?

2022-07-19 10:24 UTC, IndrajeetPatil commented
> @IndrajeetPatil Did you remove the field legendCaptionSize from default plot configuration at some point?

Yepp, it has been renamed. Already made a commit to fix this. I think that should fix the issue.

2022-07-19 10:38 UTC, merged