Documentation rework
esqLABS/esqlabsR pull request #446
Opened 2023-05-16 15:49 UTC by Felixmil

I also added some features to improve user experience. I will let you discover them by reading the documentation by opening the index file in [esqlabsR-document-rework.zip](https://github.com/esqLABS/esqlabsR/files/11489664/esqlabsR-document-rework.zip)

2023-05-17 08:04 UTC, PavelBal commented
@Felixmil I wait with review as the build is failing, right?

2023-05-17 08:10 UTC, Felixmil commented
@PavelBal You can start reviewing the documentation part. I'm fixing the test right now.

2023-05-17 08:56 UTC, PavelBal commented
- `TestProject` is now in `extdata` but also in `tests`. Then I would suggest to remove the `tests` one - should be possible to use the version in `extdata` for tests, right? Otherwise we have content duplication and I am 99% positive it will be out of sync one day.
- Currently I do not see a need for the `NewProject`, it can be as well the `TestProject`.
- Current workflow of setting up the project environment:
  - Execute the PowerShell script https://github.com/esqLABS/esqlabs-interna/blob/master/initializeProjectFolder.ps1, which at some point downloads the `{esqlabsR}` package and extracts the contents of the `TestProject` https://github.com/esqLABS/esqlabs-interna/blob/504036ddf8c52b6ce85be00e7fc0450ae9a761c9/initializeProjectFolder.ps1#L87-L109
  - Proposal - PowerShell script only creates the `"V00.01"` folder, downloads `install-packages.R` to it, and the user has to source `install-packages`. Probalby for this to work the script has be extended by a variable `projectWorkingDirectory` that will be overwritten by the PowerShell script (example how it was done in one of the previous versions:
  
```# At this point, PK-Sim has been installed. We change the links in the R scripts to match the installation path
$searchString = "pkSimPath <- NULL"
$replacementString = "pkSimPath <- `"" + $pksimPathVersion.replace('\', '\\') + "`""
$scriptPath = Join-Path $ProjectFolder "V00.01\Code\DoNotSource\install-packages.R"
if (Test-Path -Path $scriptPath) {
	$content = [System.IO.File]::ReadAllText($scriptPath).Replace($searchString, $replacementString)
	[System.IO.File]::WriteAllText($scriptPath, $content)
}```

- `install-packages` would ask the user if he would like to initialize the project folder structure, if yes -> call `init_project()`

2023-05-17 09:06 UTC, PavelBal commented
2DO:
- Update documentation on BlueSpice
- Mention how to "update" your project - create a new "VXX.XX" folder and call `init_project()` from it. This will ensure that the folder structure and all excel files are up to date. If required, compare the excel files with the old ones, adjust the old to match the new structure, and then copy them to the new folder.

2023-05-17 09:10 UTC, Felixmil commented
> * `TestProject` is now in `extdata` but also in `tests`. Then I would suggest to remove the `tests` one - should be possible to use the version in `extdata` for tests, right? Otherwise we have content duplication and I am 99% positive it will be out of sync one day.

Wanted general aprovment before deleting this directory. Tests already use the extdata folder :)



> * Currently I do not see a need for the `NewProject`, it can be as well the `TestProject`.

I think it is nice to provide the user a way to initiate a project that contains only the folder structure and the excel template without any data in it. Just much cleaner to start with.

For all other comment I think it is more related to **internal workflow** while this documentation update is both for internal and potential external users. These should be on bluespice only.

2023-05-17 09:23 UTC, PavelBal commented
> I think it is nice to provide the user a way to initiate a project that contains only the folder structure and the excel template without any data in it. Just much cleaner to start with.

But then the new project also needs all the other folders (Data, Models etc), otherwise the project would not work properly.

2023-05-17 09:29 UTC, Felixmil commented
> But then the new project also needs all the other folders (Data, Models etc), otherwise the project would not work properly.

Empty directories were not committed 🙈

2023-05-17 10:15 UTC, PavelBal requested changes

2023-05-17 10:15 UTC, PavelBal commented on vignettes/esqlabsR.Rmd
> +them using `createScenarios` and `readScenarioConfigurationFromExcel`:
```suggestion
using `createScenarios()` and `readScenarioConfigurationFromExcel()` functions:
```

2023-05-17 10:15 UTC, PavelBal commented on vignettes/esqlabsR.Rmd
> +my_simulation <- runScenarios(my_scenarios)
Rename the variable to `myScenarioResults` so there is not confusion between the `Simulation` object from `{ospsuite}` and what we are having here as results.

2023-05-17 10:15 UTC, PavelBal commented on vignettes/esqlabsR.Rmd
> +Simulation results can be saved for later use without rerun the simulation using
```suggestion
Simulation results can be saved for later use:
```

2023-05-17 10:15 UTC, PavelBal commented on vignettes/esqlabsR.Rmd
> +The simulation results can now be plotted. For this, the package relies on
This section will be re-worked when we add documentation on the plotting. For now, please add links to the vignettes on `DataCombined` and how to plot with it from the `ospsuite`, as these functionalities are rather new and not many users are familiar with them.

2023-05-17 10:15 UTC, PavelBal commented on vignettes/esqlabsR.Rmd
> +osps's datacombined and plotting functions.
```suggestion
on the concept of combining multiple simulation results and observed data using the `DataCombined` class and creating figures using functions implemented in the `{ospsuite}` package.
```

2023-05-17 10:15 UTC, PavelBal commented on vignettes/esqlabsR.Rmd
> +First, a dataCombined object is initialized:
```suggestion
First, a `DataCombined` object is initialized:
```

2023-05-17 10:15 UTC, PavelBal commented on vignettes/esqlabsR.Rmd
> +Many other plots are available in esqlabsR, read `vignette("esqlabsR-plot-results")`
```suggestion
Many other plot types are available in `{esqlabsR}`, read `vignette("esqlabsR-plot-results")` 
```

2023-05-17 10:34 UTC, Felixmil commented on R/utilities-project-configuration.R
> +test_ProjectConfiguration <- function(){
Duplicated fun removed tho.

2023-05-17 10:38 UTC, Felixmil commented on NAMESPACE
> +export(example_ProjectConfiguration)
My intention was to make `example_ProjectConfiguration` easily accessible to the user so he can directly try things out after installing the package. But also follow the vignettes as is.

2023-05-17 10:58 UTC, Felixmil commented on vignettes/data-handling.Rmd
> ----
This section was move to plotting vignette

2023-05-17 11:04 UTC, Felixmil commented on vignettes/esqlabsR.Rmd
> +```sh
Code folder is necessary for internal project structure but not for a "generic" esqlabsR project.

2023-05-17 11:20 UTC, PavelBal commented on vignettes/esqlabsR.Rmd
> +```sh
Hm that's right... but in this case, the "ProjectConfiguration" must be placed in the root project folder, not the Code folder, and `createDefaultProjectConfiguration()` should be adjusted accordingly (as the working directory will be mostly the "Code" folder).

2023-05-17 11:28 UTC, Felixmil commented on README.Rmd
> +  createDefaultProjectConfiguration(example_ProjectConfiguration())
See https://github.com/esqLABS/esqlabsR/pull/446#discussion_r1196292844

2023-05-17 11:29 UTC, Felixmil commented on R/example.R
> +#' @param path Name of file. If `NULL`, the example files will be listed.
This is a helper internal function to get easily to extdata directory. Maybe the naming is not good ?

2023-05-17 12:10 UTC, PavelBal commented on R/example.R
> +#' @param path Name of file. If `NULL`, the example files will be listed.
I mean the 

> If `NULL`, the example files will be listed.

Is not true, as the two folders of the example projects are listed, not the files within.

2023-05-31 09:04 UTC, PavelBal commented on vignettes/esqlabsR-workflow-overview.Rmd
> +This first step is here to initialize the specific directories and file
```suggestion
This first step is to initialize the specific directories and file 
```

2023-05-31 09:14 UTC, PavelBal commented on vignettes/esqlabsR-workflow-overview.Rmd
> +compose plotgrids from simulation results.
```suggestion
`esqlabsR` implements convenient and automated ways to generate various plots for visual representation of simulation results.
```

2023-06-02 13:41 UTC, PavelBal commented
@Felixmil please review my latest changes. Once the https://github.com/esqLABS/esqlabs-interna/blob/master/initializeProjectFolder.ps1 script has been adjusted, this can be merged.

2023-06-02 13:41 UTC, PavelBal approved these changes

2023-06-02 13:41 UTC, PavelBal approved these changes

2023-06-02 14:43 UTC, Felixmil commented
> @Felixmil please review my latest changes. Once the https://github.com/esqLABS/esqlabs-interna/blob/master/initializeProjectFolder.ps1 script has been adjusted, this can be merged.

Ok. I'll try to fix the branch's test. You can already review the adjusted powershell script here: https://github.com/esqLABS/esqlabs-interna/pull/2

2023-06-02 14:55 UTC, PavelBal commented
The data importer configuration was outdated, but the new version uses slightly different naming when creating data sets. A name of a data set referred to in the Plots.xlsx was invalid.

2023-06-02 15:11 UTC, merged