Small improvements to plotting vignette
esqLABS/esqlabsR pull request #531
Opened 2023-09-08 10:10 UTC by Felixmil

2023-09-13 08:29 UTC, PavelBal commented
Resolve conflicts and then merge.

2023-09-22 14:20 UTC, PavelBal requested changes

2023-09-22 14:20 UTC, PavelBal commented on docs/dev/articles/esqlabsR-plot-results_files/figure-html/plot-time-profile-1.png
@Felixmil Axis labels are now always wrapped and look very strange... Can this be fixed?

2023-09-26 15:56 UTC, PavelBal commented
Where are the conflicts coming from? Can you resolve?

2023-09-26 16:09 UTC, Felixmil commented
A vignette was changed by `{styler}`. Conflict resolved.

2023-09-28 13:13 UTC, PavelBal approved these changes

2023-09-28 13:14 UTC, merged