Pksim installation instruction
esqLABS/esqlabsR pull request #543
Opened 2023-09-22 11:51 UTC by Felixmil

To merge after #531

2023-09-28 13:43 UTC, PavelBal commented
Conflicts again :D

2023-09-28 13:51 UTC, Felixmil commented
Please review #544 so I can merge and resolve conflicts just once :)

2023-10-03 16:02 UTC, PavelBal commented on inst/extdata/examples/TestProject/Parameters/Individuals.xlsx
What is different is this file?

2023-10-04 09:30 UTC, Felixmil commented on inst/extdata/examples/TestProject/Parameters/Individuals.xlsx
This change comes from: https://github.com/esqLABS/esqlabsR/pull/544/files#diff-9aecab6b93859050a84eb1434a91a5fc91758fe89a160512f3353e3369f8608f
and was merged here when solving conflicts. 

There is actually no difference compared to the previous version. It is just that while updating parameters file for adding `nsd` example, I saved that excel file before closing it. Git detects it as different because of the `last modification date` being different though.

Once we can rely on shiny apps to setup the parameters, we should move to non binary files (csv, json) so we can track differences more easily, (+ be more aligned with our open-source philosophy  and get rid of excel 😄)

2023-10-04 15:14 UTC, PavelBal commented
Please add some rationale why this step (downloading PK-Sim etc) is required.

2023-10-05 09:36 UTC, PavelBal commented
Add instructions on how to download the latest pksim minimal (to use in the projects)

2023-10-05 10:30 UTC, Felixmil commented
> Add instructions on how to download the latest pksim minimal (to use in the projects)

Should I replace the link to pksim in the the `install-pksim.Rmd` vignette:
```
## Download PK-Sim

Download the latest portable version of PK-Sim by clicking
[here](https://ci.appveyor.com/api/projects/open-systems-pharmacology-ci/pk-sim/artifacts/pk-sim-portable-setup.zip?branch=develop).
```

to pksim-minimal link ?

Or should I create two main sections:
- General PKSIm installation (system-wide)
- Project Specific PKSim installation (with pksim minimal)

2023-10-05 10:32 UTC, PavelBal commented
> Or should I create two main sections to this vignette:

This

2023-10-05 10:58 UTC, Felixmil commented
preview:
![image](https://github.com/esqLABS/esqlabsR/assets/34234913/910d56d3-6630-4c37-99ed-16f0ebb9bd34)

2023-10-05 11:08 UTC, PavelBal commented on vignettes/install-pksim.Rmd
> +Alternatively, it is possible to add this line to a `.Rprofile` file in the
"this line" is not clear, better "the line from above" or something... I was actually waiting for the code line to be specified here

2023-10-05 11:09 UTC, Felixmil commented on vignettes/install-pksim.Rmd
> +Alternatively, it is possible to add this line to a `.Rprofile` file in the
```suggestion
Alternatively, it is possible to add the line above to a `.Rprofile` file in the
```

2023-10-05 11:09 UTC, PavelBal requested changes
Just a minor change to the pk-sim minimal description

2023-10-05 11:10 UTC, PavelBal approved these changes

2023-10-05 14:57 UTC, PavelBal approved these changes

2023-10-05 15:00 UTC, merged