Add observed data to time profiles
esqLABS/esqlabsR pull request #674
Opened 2024-05-31 16:24 UTC by rengelke

Adds a new parameter `observedData` to the function `sensitivityTimeProfiles` to include observed data in the plots. Closes #259

2024-06-03 08:29 UTC, dlefaudeux commented on R/sensivitity-time-profiles.R
> +    dplyr::filter(grepl("Concentration", Dimension))
Wondering if restricting to Concentrations is really needed?

2024-06-03 09:00 UTC, PavelBal requested changes

2024-06-03 09:00 UTC, PavelBal commented on tests/testthat/_snaps/sensitivity-time-profiles/multiple-output-path-profiles.svg
Why did the analysis results change?

Also the legend for parameter factor is incomplete now.

2024-06-03 09:36 UTC, rengelke commented on tests/testthat/_snaps/sensitivity-time-profiles/multiple-output-path-profiles.svg
I found a mistake in the previous test for multiple output paths where `results` instead of `results_multiple` (now `resultsMultiple`) is used for plotting:

``test_that("sensitivityTimeProfiles plots are as expected for multiple output paths", {
  set.seed(123)
  p_list <- sensitivityTimeProfiles(results)``

2024-06-20 10:27 UTC, PavelBal commented on R/sensivitity-time-profiles.R
> +      # add line for observed data
"add symbols"?

2024-07-18 09:33 UTC, PavelBal commented
@Felixmil hmm somehow the GHA broke? PK-Sim is not installed any more?

2024-07-18 09:38 UTC, PavelBal commented on tests/testthat/test-sensitivity-time-profiles.R
> +test_that("sensitivityTimeProfiles plots correctly for multiple outputs with multiple observed data with same dimension", {
New test added

2024-07-18 10:35 UTC, rengelke commented on R/sensivitity-time-profiles.R
>    if (!is.null(xAxisScale)) customPlotConfiguration$xAxisScale <- xAxisScale
I have completely refactored the plot configuration setup in the next PR, which I will be submitting soon.

2024-07-18 10:36 UTC, rengelke commented
> I like it! Last thing that you overlooked - adding multiple observed datasets to the same plot.

Yes, indeed. Thank you for the test :)

2024-07-19 10:58 UTC, PavelBal approved these changes

2024-07-25 16:08 UTC, Felixmil commented
Merge #683  then update this branch and check CI results

2024-07-26 09:59 UTC, merged