Fixes #85 appveyor issue
esqLABS/esqlabsR pull request #88
Opened 2021-09-29 17:01 UTC by msevestre

2021-09-29 17:02 UTC, msevestre commented on rakefile.rb
>    update_package_version(args.build_version, description_file)
That should be the only thing required. it will update the package version 2.0.0 to be 2.0.BUILD NUMBER

2021-09-29 19:37 UTC, IndrajeetPatil commented
Seems to be working now!!! 🎉

2021-09-30 07:55 UTC, PavelBal requested changes
Just one comment regarding using rClr from github repo.

2021-09-30 07:55 UTC, PavelBal commented on appveyor.yml
>    - Rscript -e "install.packages('./tools/rClr_0.9.1.zip', repos = NULL, type = 'binary')"
Can we reference the online version?:

`Rscript -e "install.packages('.https://github.com/Open-Systems-Pharmacology/rClr/releases/download/v0.9.1/rClr_0.9.1.zip', repos = NULL, type = 'binary')"`

It works locally in RStudio. This way we do not have to pack rClr in the package.

2021-09-30 07:55 UTC, PavelBal commented on rakefile.rb
>    file_name ='setup.zip'
I think PK-Sim is required for some tests that use creation of individuals. Maybe we should consider at some point to completely remove the dependency by separating the "create..." algorithms in separate submodule?

2021-09-30 16:36 UTC, msevestre commented
Lets' try

2021-09-30 18:13 UTC, msevestre commented
that works with rclr remote... damm... Going to do this for ospsuite-r too!

2021-09-30 18:16 UTC, IndrajeetPatil commented
Woot!! You sir are a genius! Thanks for getting it to work. 😅

2021-09-30 18:27 UTC, msevestre commented
ok I have added the badge for CI also (coming from Appveyor). I think this is ready to merge

2021-09-30 18:31 UTC, merged